export const MESSAGES = {
    WHATS_APP_TEXT:'AGAR APP GAME KEHLNA AGAR APP GAME KEHLNA AGAR APP GAME KEHLNA AGAR APP GAME KEHLNA'
}

export const TABLE_COLUMNS_COLOR = {
    A: "#2E8B57",
    B: "#FF4500", 
    C: "#1E90FF",
}
